backend: stop using deprecated ioutil in favor of os/io
ioutil was deprecated in favor of os/io. Fixed after seeing warnings like these
warnings from golangci:

```
cmd/playground/main.go:36:16: Error return value of `db.Close` is not checked (errcheck)
        defer db.Close()
                      ^
util/config/file.go:19:2: SA1019: package io/ioutil is deprecated: As of Go 1.16, the same functionality is now provided by package io or package os, and those implementations should be preferred in new code. See the specific function documentation for details. (staticcheck)
        "io/ioutil"
        ^
backend/coins/eth/etherscan/etherscan.go:21:2: SA1019: package io/ioutil is deprecated: As of Go 1.16, the same functionality is now provided by package io or package os, and those implementations should be preferred in new code. See the specific function documentation for details. (staticcheck)
        "io/ioutil"
        ^
util/test/test.go:20:2: SA1019: package io/ioutil is deprecated: As of Go 1.16, the same functionality is now provided by package io or package os, and those implementations should be preferred in new code. See the specific function documentation for details. (staticcheck)
        "io/ioutil"
```